<a href="https://colab.research.google.com/github/dngdat/AI/blob/main/w8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
from sklearn.linear_model import Perceptron
x = [[0,0],[0,1],[1,0],[1,1]]
t = [0,1,1,1]
# Tính độ chính xác 
model = Perceptron()
model.fit(x,t)
model.score(x,t)

1.0

In [22]:
x1 = [[0.29,0.29],[-0.5,-0.5],[10,2.3],[-1,-2]]
y1 = model.predict(x1)
model.score(x1,y1)
print(y1)

[1 0 1 0]


In [23]:
x = [[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
t1 = [1,1,1,1]
model = Perceptron()
model.fit(x,t)
model.score(x,t)

1.0

In [24]:
from os.path import split
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [25]:
# Lấy dữ liệu trên iris
iris = datasets.load_iris()
x = iris.data
y = iris.target

print(x[:5]) # hien thi ra 5 dong dau tien
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [26]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3) # lay ti le 70/30 
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)
print(x_train_std[:5], x_train[:5])
print(y[:5])

[[ 0.          0.32455484  0.5523661   0.74862035]
 [ 0.12842848 -0.77474382  0.7293705   0.48034343]
 [-1.02742782  0.98413404 -1.45368373 -1.39759498]
 [-0.12842848 -0.77474382  0.02135291 -0.0562104 ]
 [-0.51371391 -0.99460356  0.31636024 -0.0562104 ]] [[5.9 3.2 4.8 1.8]
 [6.  2.7 5.1 1.6]
 [5.1 3.5 1.4 0.2]
 [5.8 2.7 3.9 1.2]
 [5.5 2.6 4.4 1.2]]
[0 0 0 0 0]


In [27]:
model = Perceptron(max_iter = 1000000, eta0 = 0.2, random_state = 0)
#maxinter : so lan hoc
#eta0 : toc do hoc 
#randomstate : gia tri ngau nhien cua he thong
model.fit(x_train,y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(y_test)
print("Độ chính xác của mô hình:", accuracy_score(y_test, y_pred))

[2 0 2 1 0 0 0 0 2 1 0 2 0 0 2 0 2 2 0 0 1 2 0 0 2 1 1 0 2 2 2 0 2 2 1 2 2
 1 0 2 0 1 1 1 1]
[2 0 2 1 0 0 0 0 2 1 1 1 0 0 2 0 2 2 0 0 1 2 2 0 1 1 0 0 2 2 2 0 2 2 0 1 2
 1 0 2 0 1 1 0 0]
Độ chính xác của mô hình: 0.8


In [28]:
model = Perceptron(max_iter = 1000000, eta0 = 0.2, random_state = 0)
model.fit(x_train_std,y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(y_test)
print("Độ chính xác của mô hình:", accuracy_score(y_test, y_pred))

[1 0 2 1 0 0 0 0 2 1 1 1 0 0 2 0 2 2 0 0 1 2 2 0 1 0 0 0 2 2 2 0 2 2 0 1 2
 1 0 2 0 1 1 0 0]
[2 0 2 1 0 0 0 0 2 1 1 1 0 0 2 0 2 2 0 0 1 2 2 0 1 1 0 0 2 2 2 0 2 2 0 1 2
 1 0 2 0 1 1 0 0]
Độ chính xác của mô hình: 0.9555555555555556


Crabs 

In [29]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

import pandas as pd
url = 'crabs.csv'
data = pd.read_csv(url)

dataframe = data.replace(['F','M','B','O'], [0,1,1,0])
print(dataframe)

     speies  sex  index  fontallip  rearwidth  length  width  depth
0         1    1      1        8.1        6.7    16.1   19.0    7.0
1         1    1      2        8.8        7.7    18.1   20.8    7.4
2         1    1      3        9.2        7.8    19.0   22.4    7.7
3         1    1      4        9.6        7.9    20.1   23.1    8.2
4         1    1      5        9.8        8.0    20.3   23.0    8.2
..      ...  ...    ...        ...        ...     ...    ...    ...
195       0    0     46       21.4       18.0    41.2   46.2   18.7
196       0    0     47       21.7       17.1    41.7   47.2   19.6
197       0    0     48       21.9       17.2    42.6   47.4   19.5
198       0    0     49       22.5       17.2    43.0   48.7   19.8
199       0    0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]


In [30]:
x = dataframe.drop('speies', axis = 1)
y = dataframe.speies
print(x[:])
print(y[:])

     sex  index  fontallip  rearwidth  length  width  depth
0      1      1        8.1        6.7    16.1   19.0    7.0
1      1      2        8.8        7.7    18.1   20.8    7.4
2      1      3        9.2        7.8    19.0   22.4    7.7
3      1      4        9.6        7.9    20.1   23.1    8.2
4      1      5        9.8        8.0    20.3   23.0    8.2
..   ...    ...        ...        ...     ...    ...    ...
195    0     46       21.4       18.0    41.2   46.2   18.7
196    0     47       21.7       17.1    41.7   47.2   19.6
197    0     48       21.9       17.2    42.6   47.4   19.5
198    0     49       22.5       17.2    43.0   48.7   19.8
199    0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 7 columns]
0      1
1      1
2      1
3      1
4      1
      ..
195    0
196    0
197    0
198    0
199    0
Name: speies, Length: 200, dtype: int64


In [31]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3)
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)
print(x_train_std[:])
print(y.T)

[[-0.98581488  0.64817167  1.05009836  1.39391868  0.85855456  0.81936661
   0.96804746]
 [-0.98581488 -0.16750504 -0.74483721 -0.16392657 -0.54595161 -0.53136651
  -0.69431939]
 [-0.98581488  0.64817167 -0.08954327  0.33002436  0.01585086  0.11244087
  -0.02353978]
 [ 1.01438923  0.92006391  0.48027755  0.02605455  0.69001382  0.73100089
   0.50141817]
 [ 1.01438923 -0.03155892  0.25234922 -0.39190393 -0.02628433 -0.241022
   0.18061053]
 [ 1.01438923  0.64817167  0.90764316  0.29202813  0.8445095   0.73100089
   0.99721179]
 [-0.98581488 -1.25507399 -0.40294472  0.06405078 -0.41954606 -0.46824814
  -0.34434742]
 [-0.98581488 -0.98318175 -1.25767595 -1.07583599 -1.30438495 -1.3140343
  -1.6567423 ]
 [-0.98581488 -0.57534339 -1.00125658 -0.46789638 -0.81280779 -0.75859264
  -0.86930537]
 [ 1.01438923  1.05601003  0.65122379  0.36802059  0.97091505  1.05921642
   0.61807549]
 [-0.98581488  1.53182144  1.84784751  1.73588471  1.51867246  1.42530296
   1.63882707]
 [ 1.01438923 -0.6433164

In [32]:
model = Perceptron(max_iter = 1000000, eta0 = 0.2, random_state = 0)
model.fit(x_train_std, y_train)
y_pred = model.predict(x_test_std)
print(y_pred[:])
print(y_test[:].T)
print("Độ chính xác của mô hình:", accuracy_score(y_test, y_pred))

[0 1 0 1 0 0 0 1 1 1 0 1 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 1 0 1 1 1 1
 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 1 0]
143    0
35     1
132    0
6      1
170    0
113    0
133    0
58     1
25     1
64     1
118    0
100    0
131    0
167    0
166    0
82     1
110    0
23     1
10     1
49     1
161    0
135    0
105    0
128    0
180    0
104    0
21     1
70     1
93     1
162    0
27     1
24     1
192    0
65     1
90     1
9      1
55     1
144    0
171    0
79     1
41     1
45     1
181    0
158    0
43     1
139    0
83     1
145    0
168    0
51     1
157    0
172    0
195    0
126    0
189    0
182    0
188    0
17     1
53     1
142    0
Name: speies, dtype: int64
Độ chính xác của mô hình: 0.9833333333333333
